name: Deployment

on:
  push:
    branches: [master]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: wangyucode/sftp-upload-action@v2.0.2
      with:
        host: ${{ secrets.SERVER }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        compress: true 
        forceUpload: false
        localDir: ./
        remoteDir: /vhosts/rubis-mecenat.stagingserver.fr/htdocs/